# Loan Defaluters

In [1]:
import numpy as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('credit_risk_dataset.csv')

In [3]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [5]:
df.tail()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
995,53,44519.0,7307,433,22,PhD,Rent,1
996,22,107487.0,44901,582,7,High School,Own,1
997,34,102870.0,16205,372,29,Masters,Rent,0
998,60,66197.0,10906,780,24,PhD,Own,0
999,60,NaN,7591,651,5,High School,Mortgage,0

In [6]:
df.shape

(1000, 8)

In [7]:
df['Education_Level'].unique

<bound method Series.unique of 0        Bachelors
1              PhD
2          Masters
3        Bachelors
4          Masters
          ...
995            PhD
996    High School
997        Masters
998            PhD
999    High School
Name: Education_Level, Length: 1000, dtype: object>

In [8]:
order = {'Bachelors':1,'phD':3,'Masters':2,'High School':0}

In [9]:
df['Education_Level'] = df['Education_Level'].map(order)

In [11]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,1.0,Own,0
1,49,116646.0,43663,315,5,NaN,Own,0
2,35,61157.0,18994,428,8,2.0,Own,1
3,63,52154.0,28499,408,26,1.0,Rent,0
4,28,148876.0,28040,832,3,2.0,Own,1

In [13]:
df['Housing_Status'].unique()

array(['Own', 'Rent', 'Mortgage'], dtype=object)

In [20]:
df['Housing_Status'].map({'Own':2,'Rent':0,'Mortgage':1})

KeyError: 'Housing_Status'

In [ ]:
df.head()